# Generated by Django 4.1.5 on 2023-03-17 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contato_cpf_alter_contato_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_criacao',
            new_name='entrada_staff',
        ),
        migrations.AddField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
