# Generated by Django 4.1.5 on 2023-03-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_rename_data_criacao_contato_entrada_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1x'), (2, '2x_ou_mais'), (3, 'Perma')], null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
