# Generated by Django 4.1.5 on 2023-03-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_contato_role_alter_contato_cpf_alter_contato_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='role',
            new_name='Saida_staff',
        ),
    ]
